### ISSUE TITLE
pls, specify tf2_gnn version

### ISSUE THREAD

**Issue by whatsmyname** [yeguixin/POEM#1]
thanks for your good work, but when running the codes I met the following issue:

`    from tf2_gnn.cli_utils import get_train_cli_arg_parser, run_train_from_args, get_train_file
ImportError: cannot import name 'get_train_file'`

would you like to specify the version of tf2_gnn library? that would be helpful.

**Comment by yeguixin** [comment]
Good catch @whatsmyname. Thanks for pointing out this error. `tf2_gnn` should be `multi-gnn`. We will update soon.

**Comment by whatsmyname** [comment]
Thanks for your response. It works.
